# Generated by Django 5.2.7 on 2025-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('club', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=100)),
                ('pace', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('physical', models.IntegerField()),
            ],
        ),
    ]
